# Province e comuni principali d'Italia
# Struttura: provincia -> lista comuni
ITALY_LOCATIONS = {
    "Agrigento": ["Agrigento", "Licata", "Canicattì", "Sciacca", "Favara"],
    "Alessandria": ["Alessandria", "Casale Monferrato", "Novi Ligure", "Tortona", "Valenza"],
    "Ancona": ["Ancona", "Jesi", "Senigallia", "Fabriano", "Osimo"],
    "Arezzo": ["Arezzo", "Cortona", "San Giovanni Valdarno", "Montevarchi", "Bibbiena"],
    "Ascoli Piceno": ["Ascoli Piceno", "San Benedetto del Tronto", "Grottammare"],
    "Asti": ["Asti", "Nizza Monferrato", "Canelli", "San Damiano d'Asti"],
    "Avellino": ["Avellino", "Ariano Irpino", "Mercogliano", "Monteforte Irpino"],
    "Bari": ["Bari", "Molfetta", "Altamura", "Monopoli", "Bitonto", "Modugno"],
    "Belluno": ["Belluno", "Feltre", "Cortina d'Ampezzo", "Agordo"],
    "Benevento": ["Benevento", "Montesarchio", "San Giorgio del Sannio"],
    "Bergamo": ["Bergamo", "Treviglio", "Seriate", "Dalmine", "Romano di Lombardia"],
    "Biella": ["Biella", "Cossato", "Cavaglià", "Candelo"],
    "Bologna": ["Bologna", "Imola", "Casalecchio di Reno", "San Lazzaro di Savena", "Castel Maggiore"],
    "Bolzano": ["Bolzano", "Merano", "Bressanone", "Brunico", "Laives"],
    "Brescia": ["Brescia", "Desenzano del Garda", "Montichiari", "Lumezzane", "Palazzolo sull'Oglio"],
    "Brindisi": ["Brindisi", "Fasano", "Francavilla Fontana", "Ostuni", "Mesagne"],
    "Cagliari": ["Cagliari", "Quartu Sant'Elena", "Assemini", "Capoterra", "Selargius"],
    "Caltanissetta": ["Caltanissetta", "Gela", "Mussomeli", "Niscemi"],
    "Campobasso": ["Campobasso", "Termoli", "Isernia", "Venafro"],
    "Caserta": ["Caserta", "Aversa", "Marcianise", "Santa Maria Capua Vetere", "Maddaloni"],
    "Catania": ["Catania", "Acireale", "Paternò", "Misterbianco", "Adrano"],
    "Catanzaro": ["Catanzaro", "Lamezia Terme", "Soverato", "Chiaravalle Centrale"],
    "Chieti": ["Chieti", "Lanciano", "Vasto", "Francavilla al Mare", "Ortona"],
    "Como": ["Como", "Cantù", "Erba", "Mariano Comense", "Lomazzo"],
    "Cosenza": ["Cosenza", "Rende", "Rossano", "Corigliano Calabro", "Castrovillari"],
    "Cremona": ["Cremona", "Crema", "Casalmaggiore", "Soresina"],
    "Crotone": ["Crotone", "Cirò Marina", "Cutro", "Isola di Capo Rizzuto"],
    "Cuneo": ["Cuneo", "Alba", "Bra", "Fossano", "Mondovì"],
    "Enna": ["Enna", "Piazza Armerina", "Leonforte", "Nicosia"],
    "Fermo": ["Fermo", "Porto Sant'Elpidio", "Porto San Giorgio", "Montegranaro"],
    "Ferrara": ["Ferrara", "Cento", "Comacchio", "Bondeno"],
    "Firenze": ["Firenze", "Scandicci", "Sesto Fiorentino", "Empoli", "Campi Bisenzio"],
    "Foggia": ["Foggia", "Cerignola", "Manfredonia", "San Severo", "Lucera"],
    "Forlì-Cesena": ["Forlì", "Cesena", "Cesenatico", "Forlimpopoli"],
    "Frosinone": ["Frosinone", "Cassino", "Ferentino", "Anagni", "Sora"],
    "Genova": ["Genova", "Chiavari", "Rapallo", "Sestri Levante", "Lavagna"],
    "Gorizia": ["Gorizia", "Monfalcone", "Gradisca d'Isonzo"],
    "Grosseto": ["Grosseto", "Follonica", "Orbetello", "Castiglione della Pescaia"],
    "Imperia": ["Imperia", "Sanremo", "Ventimiglia", "Bordighera"],
    "L'Aquila": ["L'Aquila", "Avezzano", "Sulmona", "Celano"],
    "La Spezia": ["La Spezia", "Sarzana", "Lerici", "Levanto"],
    "Latina": ["Latina", "Aprilia", "Terracina", "Formia", "Fondi"],
    "Lecce": ["Lecce", "Nardò", "Gallipoli", "Galatina", "Maglie"],
    "Lecco": ["Lecco", "Merate", "Calolziocorte", "Bellano"],
    "Livorno": ["Livorno", "Piombino", "Cecina", "Rosignano Marittimo"],
    "Lodi": ["Lodi", "Codogno", "Sant'Angelo Lodigiano", "Casalpusterlengo"],
    "Lucca": ["Lucca", "Viareggio", "Capannori", "Altopascio"],
    "Macerata": ["Macerata", "Civitanova Marche", "Corridonia", "Tolentino"],
    "Mantova": ["Mantova", "Castiglione delle Stiviere", "Suzzara", "Viadana"],
    "Massa-Carrara": ["Massa", "Carrara", "Pontremoli", "Aulla"],
    "Matera": ["Matera", "Policoro", "Pisticci", "Nova Siri"],
    "Messina": ["Messina", "Barcellona Pozzo di Gotto", "Milazzo", "Patti"],
    "Milano": ["Milano", "Sesto San Giovanni", "Cinisello Balsamo", "Rho", "Monza"],
    "Modena": ["Modena", "Sassuolo", "Formigine", "Carpi", "Vignola"],
    "Napoli": ["Napoli", "Torre del Greco", "Pozzuoli", "Casoria", "Afragola"],
    "Novara": ["Novara", "Borgomanero", "Arona", "Galliate"],
    "Nuoro": ["Nuoro", "Siniscola", "Macomer", "Orosei", "Dorgali"],
    "Oristano": ["Oristano", "Terralba", "Cabras", "Bosa", "Ghilarza"],
    "Padova": ["Padova", "Cittadella", "Abano Terme", "Monselice", "Este"],
    "Palermo": ["Palermo", "Bagheria", "Carini", "Partinico", "Termini Imerese"],
    "Parma": ["Parma", "Fidenza", "Salsomaggiore Terme", "Collecchio"],
    "Pavia": ["Pavia", "Vigevano", "Voghera", "Mortara"],
    "Perugia": ["Perugia", "Terni", "Foligno", "Città di Castello", "Assisi"],
    "Pesaro e Urbino": ["Pesaro", "Urbino", "Fano", "Gabicce Mare"],
    "Pescara": ["Pescara", "Montesilvano", "Spoltore", "Città Sant'Angelo"],
    "Piacenza": ["Piacenza", "Castel San Giovanni", "Fiorenzuola d'Arda", "Rottofreno"],
    "Pisa": ["Pisa", "Pontedera", "Volterra", "San Giuliano Terme"],
    "Pistoia": ["Pistoia", "Montecatini Terme", "Quarrata", "Monsummano Terme"],
    "Pordenone": ["Pordenone", "Sacile", "Maniago", "Cordenons"],
    "Potenza": ["Potenza", "Melfi", "Lauria", "Rionero in Vulture"],
    "Prato": ["Prato", "Montemurlo", "Carmignano", "Poggio a Caiano"],
    "Ragusa": ["Ragusa", "Vittoria", "Modica", "Comiso", "Pozzallo"],
    "Ravenna": ["Ravenna", "Faenza", "Lugo", "Cervia"],
    "Reggio Calabria": ["Reggio Calabria", "Gioia Tauro", "Palmi", "Locri", "Siderno"],
    "Reggio Emilia": ["Reggio Emilia", "Scandiano", "Castelnovo ne' Monti", "Correggio"],
    "Rieti": ["Rieti", "Cittaducale", "Poggio Mirteto", "Magliano Sabina"],
    "Rimini": ["Rimini", "Riccione", "Cattolica", "Bellaria-Igea Marina"],
    "Roma": ["Roma", "Fiumicino", "Guidonia Montecelio", "Tivoli", "Pomezia"],
    "Rovigo": ["Rovigo", "Adria", "Porto Viro", "Badia Polesine"],
    "Salerno": ["Salerno", "Cava de' Tirreni", "Battipaglia", "Eboli", "Nocera Inferiore"],
    "Sassari": ["Sassari", "Alghero", "Olbia", "Porto Torres", "Tempio Pausania"],
    "Savona": ["Savona", "Albenga", "Finale Ligure", "Loano"],
    "Siena": ["Siena", "Poggibonsi", "Colle di Val d'Elsa", "Montepulciano"],
    "Siracusa": ["Siracusa", "Augusta", "Avola", "Noto", "Lentini"],
    "Sondrio": ["Sondrio", "Morbegno", "Tirano", "Chiavenna"],
    "Sud Sardegna": ["Carbonia", "Iglesias", "Santadi", "San Giovanni Suergiu"],
    "Taranto": ["Taranto", "Grottaglie", "Manduria", "Massafra"],
    "Teramo": ["Teramo", "Giulianova", "Roseto degli Abruzzi", "Alba Adriatica"],
    "Terni": ["Terni", "Orvieto", "Narni", "Amelia"],
    "Torino": ["Torino", "Moncalieri", "Rivoli", "Collegno", "Settimo Torinese"],
    "Trapani": ["Trapani", "Marsala", "Mazara del Vallo", "Alcamo", "Castelvetrano"],
    "Trento": ["Trento", "Rovereto", "Pergine Valsugana", "Arco", "Riva del Garda"],
    "Treviso": ["Treviso", "Conegliano", "Vittorio Veneto", "Montebelluna", "Castelfranco Veneto"],
    "Trieste": ["Trieste", "Muggia", "Duino-Aurisina"],
    "Udine": ["Udine", "Lignano Sabbiadoro", "Cividale del Friuli", "Gemona del Friuli"],
    "Varese": ["Varese", "Busto Arsizio", "Gallarate", "Saronno", "Tradate"],
    "Venezia": ["Venezia", "Mestre", "Chioggia", "Mira", "San Donà di Piave"],
    "Verbano-Cusio-Ossola": ["Verbania", "Domodossola", "Omegna", "Gravellona Toce"],
    "Vercelli": ["Vercelli", "Borgosesia", "Santhià", "Trino"],
    "Verona": ["Verona", "San Bonifacio", "Villafranca di Verona", "Legnago"],
    "Vibo Valentia": ["Vibo Valentia", "Tropea", "Serra San Bruno"],
    "Vicenza": ["Vicenza", "Bassano del Grappa", "Schio", "Thiene", "Arzignano"],
    "Viterbo": ["Viterbo", "Civita Castellana", "Montefiascone", "Tarquinia"]
}

def get_provinces():
    """Ritorna lista ordinata di province"""
    return sorted(ITALY_LOCATIONS.keys())

def get_cities(province):
    """Ritorna lista comuni per provincia specifica"""
    return sorted(ITALY_LOCATIONS.get(province, []))
